### PR TITLE
Added Favicons,Preloader and Updated Readme and Contributors file

### PR DESCRIPTION
**Pull request by Pargat-Dhanjal**
Added Favicons To the site
Screenshot 2022-10-01 at 8 53 20 PM

Added a Preloader for the website

https://user-images.githubusercontent.com/54456304/193416484-7bdd7a57-cbd2-49ab-9135-e064035242a6.mp4

### CODE REVIEW

**Comment by Pargat-Dhanjal** [comment]
@aditya-singh9 Issue Fix #10

**Comment by aditya-singh9** [comment]
I havent merged it yer, so it wont count for hacktoberfest

You shouldnt close it without the pr being merged

**Comment by Pargat-Dhanjal** [comment]
@aditya-singh9 There were some merge conflicts hence I closed it so as to avoid any conflicts

**Comment by Pargat-Dhanjal** [comment]
@aditya-singh9 I have Re-Opened the same and I ressolved the conflicts : )

**Pull request merged**
