### PR TITLE
added a hamburger for the small screen device

### PR DESCRIPTION
**Pull request by Nincompup**
Fixes issue #46 : 

https://user-images.githubusercontent.com/114563503/193919235-4dc74fed-400c-4c6e-a23d-70ee501b966a.mp4

### CODE REVIEW

**Comment by aditya-singh9** [comment]
Add the login and signup buttons just below the searchbar and in centre.

Fix the search button icon too

**Comment by Nincompup** [comment]
Is it okay like this:

https://user-images.githubusercontent.com/114563503/194401784-987a5d77-ac3e-471f-9d01-5f866a6a5d12.mp4

**Comment by aditya-singh9** [comment]
Yep, seems cool
Please resolve merge conflicts

**Comment by Nincompup** [comment]
Hey I have solved merge conflicts
please have a look on it

**Pull request merged**
